/** 단위 : 밀리초 */
export const ONE_MINUTE_FOR_TANSTACK = 1000 * 60;
export const ONE_HOUR_FOR_TANSTACK = 60 * ONE_MINUTE_FOR_TANSTACK;
export const ONE_DAY_FOR_TANSTACK = 24 * ONE_HOUR_FOR_TANSTACK;

/** 단위 : 초 */
export const ONE_MINUTE_FOR_SESSION = 60;
export const ONE_HOUR_FOR_SESSION = 60 * ONE_MINUTE_FOR_SESSION;
export const ONE_DAY_FOR_SESSION = 24 * ONE_HOUR_FOR_SESSION;

/** 쿠키 만료 시간 */
export const ACCESS_TOKEN_MAX_AGE = 30 * ONE_MINUTE_FOR_SESSION;
export const REFRESH_TOKEN_MAX_AGE = 7 * ONE_DAY_FOR_SESSION;
