import "./globals.css";
import { DISCLOSURE_ROOT_ID } from "@/constants/dom";
import { MockProvider } from "@/providers/MockProvider";
import QueryProvider from "@/providers/QueryProvider";
import type { Metadata } from "next";
import localFont from "next/font/local";

const pretendard = localFont({
  src: "./../assets/fonts/PretendardVariable.woff2",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html
      lang="ko"
      className={`${pretendard.className} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <MockProvider>
          <QueryProvider>
            {children}
            <div id={DISCLOSURE_ROOT_ID}></div>
          </QueryProvider>
        </MockProvider>
      </body>
    </html>
  );
}
